name: starter_template
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  chaleno: ^0.0.7
  console_bars: ^1.2.0
  equatable: ^2.0.5
  pocketbase: ^0.11.0
  uuid: ^4.4.2

dev_dependencies:
  lints: ^2.0.0
